rm -rf logs 
mkdir -p logs
cd logs
echo Collecting logs...
for f in ../../results/*.tgz
do
    (echo $f | grep -q E_0.0001) && continue;
    tar xfz $f
    dir=`tar tfz $f | head -1`
    new_dir=`echo $dir | awk -F. '{for (i = 1; $i != "slash"; i++); printf("%s", $(i + 2)); for (i += 3; i <= NF; i++) printf(".%s", $i); printf("\n")}'`
    mv $dir $new_dir || exit
    cd $new_dir || exit
    rm -f *solved.txt lps_and_sols.tgz
    ls *.full.time.log > /dev/null 2>&1 || rm -f *.full.log
    (echo $f | grep -q E_) && { mv *12.0.1.log `echo *12.0.1.log | sed -e 's/.12.0.1.log/.log/g'`; mv *12.0.1.time.log `echo *12.0.1.time.log | sed -e 's/.12.0.1.time.log/.time.log/g'`;  }
    cd ..
done
cd ..
# echo Creating tgzs...
# for d in logs/*
# do
#     echo $d
#     tar cfz tgz/$(basename $d).tgz $d
# done
tar cfz overall.tgz logs/
echo Collapsing results.csv
awk -F, 'FNR == 1{
    nodes_thr = 10000;
    for (i = 1; i <= NF; i++) {
	cols[$i] = i;
    }
    num_selected = 1;
    selected[num_selected++] = cols["name"]; selected[num_selected++] = cols["notes"]; selected[num_selected++] = cols["no_red_nodes"]; selected[num_selected++] = cols["no_red_edges"]; selected[num_selected++] = cols["reach_chain_nodes"]; selected[num_selected++] = cols["reach_chain_edges"]; selected[num_selected++] = cols["detour_nodes"]; selected[num_selected++] = cols["detour_edges"]; selected[num_selected++] = cols["no_red_time"]; selected[num_selected++] = cols["reach_chain_time"]; selected[num_selected++] = cols["detour_time"]; selected[num_selected++] = cols["all_time"]; selected[num_selected++] = cols["all_write_time"]; selected[num_selected++] = cols["no_red_mem_peak"]; selected[num_selected++] = cols["reach_chain_mem_peak"]; selected[num_selected++] = cols["detour_mem_peak"]; selected[num_selected++] = cols["all_mem_peak"]; selected[num_selected++] = cols["all_write_mem_peak"];
    for (j = 1; j <= 10; j++) {
	selected[num_selected++] = cols["B_"j]; selected[num_selected++] = cols["Obj_"j]; selected[num_selected++] = cols["time_no_red_"j]; selected[num_selected++] = cols["time_reach_chain_detour_10"]"|"cols["time_reach_chain_detour_adj_"j]; rename_sel[num_selected - 1] = "time_red_"j; selected[num_selected++] = cols["mem_no_red_"j]; selected[num_selected++] = cols["mem_reach_chain_detour_10"]"|"cols["mem_reach_chain_detour_adj_"j]; rename_sel[num_selected - 1] = "mem_red_"j; selected[num_selected++] = cols["Obj_no_red_"j"_2"]; rename_sel[num_selected - 1] = "Obj_approx_"j; selected[num_selected++] = cols["new_time_no_red_"j"_2"]; rename_sel[num_selected - 1] = "time_approx_"j; selected[num_selected++] = cols["new_mem_no_red_"j"_2"]; rename_sel[num_selected - 1] = "mem_approx_"j; selected[num_selected++] = cols["new_num_iter_no_red_"j"_2"]; rename_sel[num_selected - 1] = "num_iter_approx_"j; 
    }
    for (i = 1; i < num_selected; i++) 
	printf("%s,", (i in rename_sel)? rename_sel[i] : $(selected[i]));
    printf("\n");
}
$(cols["no_red_nodes"]) >= nodes_thr && FNR > 1{
    for (i = 1; i < num_selected; i++) {
	num = split(selected[i], a, "|");
	if (num == 1) {
	    if (index($(selected[i]), "killed: 137 (timeout)")) 
		printf("timeout for reductions,");
	    else if (index($(selected[i]), "killed: 134 (reachability)")) 
		printf("timeout for LP creation without reductions,");
	    else if ($(selected[i]) == "no file res" || $(selected[i]) == "no file res eps" || $(selected[i]) == "single missing") 
		printf("N/A,"); #typically out of mem
	    else
		printf("%s,", $(selected[i]) != ""? $(selected[i]) : "N/A");
	}
	else {
	    if ($(a[2]) != "")
		printf("%s,", $(a[2]));
	    else
		printf("%s,", $(a[1]) != ""? $(a[1]) : "N/A");
	}
    }
    printf("\n");
}' results.csv > results_site.csv

# name
# notes
# no_red_time
# reach_chain_time
# detour_time
# all_time
# all_write_time
# final_time
# no_red_el_time
# reach_chain_el_time
# detour_el_time
# all_el_time
# all_write_el_time
# final_el_time
# no_red_mem
# reach_chain_mem
# detour_mem
# all_mem
# all_write_mem
# final_mem
# no_red_mem_peak
# reach_chain_mem_peak
# detour_mem_peak
# all_mem_peak
# all_write_mem_peak
# final_mem_peak
# no_red_nodes
# no_red_edges
# no_red_from_s
# no_red_to_t
# reach_chain_nodes
# reach_chain_edges
# reach_chain_from_s
# reach_chain_to_t
# detour_nodes
# detour_edges
# detour_from_s
# detour_to_t
# B_1
# Obj_1
# time_no_red_1
# time_reach_chain_detour_1
# time_reach_chain_detour_adj_1
# mem_no_red_1
# mem_reach_chain_detour_1
# mem_reach_chain_detour_adj_1
# B_2
# Obj_2
# time_no_red_2
# time_reach_chain_detour_2
# time_reach_chain_detour_adj_2
# mem_no_red_2
# mem_reach_chain_detour_2
# mem_reach_chain_detour_adj_2
# B_3
# Obj_3
# time_no_red_3
# time_reach_chain_detour_3
# time_reach_chain_detour_adj_3
# mem_no_red_3
# mem_reach_chain_detour_3
# mem_reach_chain_detour_adj_3
# B_4
# Obj_4
# time_no_red_4
# time_reach_chain_detour_4
# time_reach_chain_detour_adj_4
# mem_no_red_4
# mem_reach_chain_detour_4
# mem_reach_chain_detour_adj_4
# B_5
# Obj_5
# time_no_red_5
# time_reach_chain_detour_5
# time_reach_chain_detour_adj_5
# mem_no_red_5
# mem_reach_chain_detour_5
# mem_reach_chain_detour_adj_5
# B_6
# Obj_6
# time_no_red_6
# time_reach_chain_detour_6
# time_reach_chain_detour_adj_6
# mem_no_red_6
# mem_reach_chain_detour_6
# mem_reach_chain_detour_adj_6
# B_7
# Obj_7
# time_no_red_7
# time_reach_chain_detour_7
# time_reach_chain_detour_adj_7
# mem_no_red_7
# mem_reach_chain_detour_7
# mem_reach_chain_detour_adj_7
# B_8
# Obj_8
# time_no_red_8
# time_reach_chain_detour_8
# time_reach_chain_detour_adj_8
# mem_no_red_8
# mem_reach_chain_detour_8
# mem_reach_chain_detour_adj_8
# B_9
# Obj_9
# time_no_red_9
# time_reach_chain_detour_9
# time_reach_chain_detour_adj_9
# mem_no_red_9
# mem_reach_chain_detour_9
# mem_reach_chain_detour_adj_9
# B_10
# Obj_10
# time_no_red_10
# time_reach_chain_detour_10
# time_reach_chain_detour_adj_10
# mem_no_red_10
# mem_reach_chain_detour_10
# mem_reach_chain_detour_adj_10
# eps_1_1
# Obj_no_red_1_1
# new_time_no_red_1_1
# new_mem_no_red_1_1
# new_num_iter_no_red_1_1
# eps_1_2
# Obj_no_red_1_2
# new_time_no_red_1_2
# new_mem_no_red_1_2
# new_num_iter_no_red_1_2
# eps_2_1
# Obj_no_red_2_1
# new_time_no_red_2_1
# new_mem_no_red_2_1
# new_num_iter_no_red_2_1
# eps_2_2
# Obj_no_red_2_2
# new_time_no_red_2_2
# new_mem_no_red_2_2
# new_num_iter_no_red_2_2
# eps_3_1
# Obj_no_red_3_1
# new_time_no_red_3_1
# new_mem_no_red_3_1
# new_num_iter_no_red_3_1
# eps_3_2
# Obj_no_red_3_2
# new_time_no_red_3_2
# new_mem_no_red_3_2
# new_num_iter_no_red_3_2
# eps_4_1
# Obj_no_red_4_1
# new_time_no_red_4_1
# new_mem_no_red_4_1
# new_num_iter_no_red_4_1
# eps_4_2
# Obj_no_red_4_2
# new_time_no_red_4_2
# new_mem_no_red_4_2
# new_num_iter_no_red_4_2
# eps_5_1
# Obj_no_red_5_1
# new_time_no_red_5_1
# new_mem_no_red_5_1
# new_num_iter_no_red_5_1
# eps_5_2
# Obj_no_red_5_2
# new_time_no_red_5_2
# new_mem_no_red_5_2
# new_num_iter_no_red_5_2
# eps_6_1
# Obj_no_red_6_1
# new_time_no_red_6_1
# new_mem_no_red_6_1
# new_num_iter_no_red_6_1
# eps_6_2
# Obj_no_red_6_2
# new_time_no_red_6_2
# new_mem_no_red_6_2
# new_num_iter_no_red_6_2
# eps_7_1
# Obj_no_red_7_1
# new_time_no_red_7_1
# new_mem_no_red_7_1
# new_num_iter_no_red_7_1
# eps_7_2
# Obj_no_red_7_2
# new_time_no_red_7_2
# new_mem_no_red_7_2
# new_num_iter_no_red_7_2
# eps_8_1
# Obj_no_red_8_1
# new_time_no_red_8_1
# new_mem_no_red_8_1
# new_num_iter_no_red_8_1
# eps_8_2
# Obj_no_red_8_2
# new_time_no_red_8_2
# new_mem_no_red_8_2
# new_num_iter_no_red_8_2
# eps_9_1
# Obj_no_red_9_1
# new_time_no_red_9_1
# new_mem_no_red_9_1
# new_num_iter_no_red_9_1
# eps_9_2
# Obj_no_red_9_2
# new_time_no_red_9_2
# new_mem_no_red_9_2
# new_num_iter_no_red_9_2
# eps_10_1
# Obj_no_red_10_1
# new_time_no_red_10_1
# new_mem_no_red_10_1
# new_num_iter_no_red_10_1
# eps_10_2
# Obj_no_red_10_2
# new_time_no_red_10_2
# new_mem_no_red_10_2
# new_num_iter_no_red_10_2
